---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - praxis.dev
  resources:
  - incidents
  - remediationplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - praxis.dev
  resources:
  - incidents/finalizers
  - remediationplans/finalizers
  verbs:
  - update
- apiGroups:
  - praxis.dev
  resources:
  - incidents/status
  - remediationplans/status
  verbs:
  - get
  - patch
  - update
