apiVersion: praxis.dev/v1alpha1
kind: Incident
metadata:
  labels:
    app.kubernetes.io/name: praxis
    app.kubernetes.io/managed-by: kustomize
  name: incident-sample
spec:
  # TODO(user): Add fields here
